version: '3.8'

services:
  db:
    image: postgres:15
    platform: linux/amd64
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: wiktor
      POSTGRES_PASSWORD: tajnehaslo
      POSTGRES_DB: moja_baza
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

  backend:
    image: kawixking/ioioio-backend:latest
    container_name: kotlin-backend
    platform: linux/amd64
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/moja_baza
      DB_USER: wiktor
      DB_PASSWORD: tajnehaslo
    ports:
      - "8080:8080"

  frontend:
    environment:
      - VITE_API_BASE_URL=/api
    image: kawixking/ioioio-frontend:latest
    container_name: vite-frontend
    platform: linux/amd64
    depends_on:
      - backend
    ports:
      - "80:80" # Azure expects web apps to be on port 80

volumes:
  pgdata:
