services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: wiktor
      POSTGRES_PASSWORD: tajnehaslo
      POSTGRES_DB: moja_baza
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wiktor -d moja_baza"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./app/server/IO
    container_name: kotlin-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/moja_baza
      DB_USER: wiktor
      DB_PASSWORD: tajnehaslo
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./app/client
    container_name: nginx-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
